theme: jekyll-theme-minimal
title: Gabriel Oliveira Alves
description: Link[Home Page](/README.md) <br>
Materials <br>
Misc <br>
future: true
header_pages:
  - README.md
  - teste.md
github:
  is_project_page: false
